server:
  port: 8002  # 视频服务端口
  tomcat:
    threads:
      max: 500  # 最大线程数
      min-spare: 100  # 最小空闲线程数
    connection-timeout: 10000  # 连接超时时间（毫秒）
    max-connections: 20000  # 最大连接数
    accept-count: 1000  # 等待队列长度
    keep-alive-timeout: 60000  # 保持连接超时时间（毫秒）

#spring:
#  kafka:
#    bootstrap-servers: 192.168.116.132:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      retries: 3
#    consumer:
#      group-id: didadida-video-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      auto-offset-reset: earliest

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.didadida.video.entity

